FIFA_TO_COUNTRY = {
    "WAL": "Wales",
    "ENG": "England",
    "SCO": "Scotland",
    "NIR": "Northern Ireland",
    "ALG": "Algeria",
    "CIV": "Ivory Coast",
    "CGO": "Congo",
    "COD": "DR Congo",
    "GER": "Germany",
    "POR": "Portugal",
    "CRO": "Croatia",
    "SUI": "Switzerland",
    "DEN": "Denmark",
    "SWE": "Sweden",
    "NED": "Netherlands",
    "IRN": "Iran",
    "KSA": "Saudi Arabia",
    "CHN": "China",
    "KOR": "South Korea",
    "JPN": "Japan",
    "RSA": "South Africa",
    "AUS": "Australia",
    "NZL": "New Zealand",
    "ARG": "Argentina",
    "BRA": "Brazil",
    "CHI": "Chile",
    "COL": "Colombia",
    "ECU": "Ecuador",
    "PAR": "Paraguay",
    "PER": "Peru",
    "URU": "Uruguay",
    "VEN": "Venezuela",
    "MEX": "Mexico",
    "USA": "United States",
    "CAN": "Canada",
    "CRC": "Costa Rica",
    "HON": "Honduras",
    "JAM": "Jamaica",
    "PAN": "Panama",
    "TRI": "Trinidad and Tobago",
    "SKN": "Saint Kitts and Nevis",
    "LCA": "Saint Lucia",
    "VIN": "Saint Vincent and the Grenadines",
    "SAM": "Samoa",
    "SMR": "San Marino",
    "STP": "São Tomé and Príncipe",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SEY": "Seychelles",
    "SLE": "Sierra Leone",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SOL": "Solomon Islands",
    "SOM": "Somalia",
    "SSD": "South Sudan",
    "ESP": "Spain",
    "SRI": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SYR": "Syria",
    "TAH": "Tahiti",
    "TJK": "Tajikistan",
    "TAN": "Tanzania",
    "THA": "Thailand",
    "TOG": "Togo",
    "TGA": "Tonga",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TKM": "Turkmenistan",
    "TCA": "Turks and Caicos Islands",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "UAE": "United Arab Emirates",
    "VIR": "U.S. Virgin Islands",
    "UZB": "Uzbekistan",
    "VAN": "Vanuatu",
    "VIE": "Vietnam",
    "YEM": "Yemen",
    "ZAM": "Zambia",
    "ZIM": "Zimbabwe",
    "BES": "Bonaire",
    "BOE": "Bonaire",
    "GUF": "French Guiana",
    "GLP": "Guadeloupe",
    "KIR": "Kiribati",
    "MTQ": "Martinique",
    "NIU": "Niue",
    "MNP": "Northern Mariana Islands",
    "NMI": "Northern Mariana Islands",
    "REU": "Réunion",
    "MAF": "Saint Martin",
    "SMN": "Saint Martin",
    "SXM": "Sint Maarten",
    "SMA": "Sint Maarten",
    "TUV": "Tuvalu",
    "ZAN": "Zanzibar",
    "ALA": "Åland",
    "BSQ": "Basque Country",
    "CAT": "Catalonia",
    "FLK": "Falkland Islands",
    "FIS": "Falkland Islands",
    "GBR": "Great Britain",
    "GOZ": "Gozo",
    "GRL": "Greenland",
    "GGY": "Guernsey",
    "JER": "Jersey",
    "IOM": "Isle of Man",
    "MHL": "Marshall Islands",
    "FSM": "Micronesia",
    "MON": "Monaco",
    "MCO": "Monaco",
    "NRU": "Nauru",
    "NCY": "Northern Cyprus",
    "TRNC": "Northern Cyprus",
    "PLW": "Palau",
    "BLM": "Saint Barthélemy",
    "SPM": "Saint Pierre and Miquelon",
    "SHN": "Saint Helena",
    "SRD": "Sardinia",
    "SAR": "Sardinia",
    "PMR": "Transnistria",
    "TOK": "Tokelau",
    "VAT": "Vatican City",
    "WLF": "Wallis and Futuna",
    "WAF": "Wallis and Futuna",
    "ESH": "Western Sahara",
    "SADR": "Western Sahara",
    "AFG": "Afghanistan",
    "AIA": "Anguilla",
    "ALB": "Albania",
    "AND": "Andorra",
    "ANG": "Angola",
    "ARM": "Armenia",
    "ARU": "Aruba",
    "ASA": "American Samoa",
    "ATG": "Antigua and Barbuda",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BAH": "Bahamas",
    "BAN": "Bangladesh",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BER": "Bermuda",
    "BHU": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BOT": "Botswana",
    "BRA": "Brazil",
    "BRU": "Brunei",
    "BUL": "Bulgaria",
    "BFA": "Burkina Faso",
    "CAM": "Cambodia",
    "CMR": "Cameroon",
    "CPV": "Cape Verde",
    "CAY": "Cayman Islands",
    "CTA": "Central African Republic",
    "CHA": "Chad",
    "CHN": "China",
    "COL": "Colombia",
    "COM": "Comoros",
    "COK": "Cook Islands",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FRO": "Faroe Islands",
    "FIJ": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GAB": "Gabon",
    "GAM": "Gambia",
    "GEO": "Georgia",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GRE": "Greece",
    "GRN": "Grenada",
    "GUM": "Guam",
    "GUA": "Guatemala",
    "GUI": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HAI": "Haiti",
    "HKG": "Hong Kong",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRQ": "Iraq",
    "ISR": "Israel",
    "ITA": "Italy",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KOS": "Kosovo",
    "KUW": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LAO": "Laos",
    "LVA": "Latvia",
    "LIB": "Lebanon",
    "LES": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MAC": "Macau",
    "MAD": "Madagascar",
    "MWI": "Malawi",
    "MAS": "Malaysia",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MTN": "Mauritania",
    "MRI": "Mauritius",
    "MDA": "Moldova",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MSR": "Montserrat",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "MYA": "Myanmar",
    "NAM": "Namibia",
    "NEP": "Nepal",
    "NCL": "New Caledonia",
    "NCA": "Nicaragua",
    "NIG": "Niger",
    "NGA": "Nigeria",
    "PRK": "North Korea",
    "MKD": "North Macedonia",
    "NOR": "Norway",
    "OMA": "Oman",
    "PAK": "Pakistan",
    "PLE": "Palestine",
    "PAN": "Panama",
    "PHI": "Philippines",
    "POL": "Poland",
    "PUR": "Puerto Rico",
    "QAT": "Qatar",
    "IRL": "Republic of Ireland",
    "ROU": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SLV": "El Salvador",
    "SWZ": "Eswatini",
    "TLS": "Timor-Leste",
    "TPE": "Chinese Taipei",
    "VGB": "British Virgin Islands",
    "BHR": "Bahrain",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BRB": "Barbados",
    "EQG": "Equatorial Guinea",
    "ERI": "Eritrea",
    "PNG": "Papua New Guinea"
}

PROVINCE_LOOKUP = {
    "CB": "Córdoba Province",
    "BS": "Buenos Aires Province",
    "SF": "Santa Fe Province",
}